--
-- Create table `sales`
--
CREATE TABLE sales (
  ID INT NOT NULL AUTO_INCREMENT,
  Region VARCHAR(50) DEFAULT NULL,
  Country VARCHAR(50) DEFAULT NULL,
  ItemType VARCHAR(50) DEFAULT NULL,
  SalesChannel VARCHAR(50) DEFAULT NULL,
  OrderPriority VARCHAR(50) DEFAULT NULL,
  OrderDate VARCHAR(50) DEFAULT NULL,
  OrderID VARCHAR(50) DEFAULT NULL,
  ShipDate VARCHAR(50) DEFAULT NULL,
  UnitSold VARCHAR(50) DEFAULT NULL,
  UnitPrice VARCHAR(50) DEFAULT NULL,
  UnitCost VARCHAR(50) DEFAULT NULL,
  TotalRevenue VARCHAR(50) DEFAULT NULL,
  TotalCost VARCHAR(50) DEFAULT NULL,
  TotalProfit VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17979,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;